package com.example.clockee_server.message;

/** MessageKey */
public enum MessageKey {
  RESOURCE_NOT_FOUND,
  BAD_REQUEST,
  INVALID_EMAIL,
  EMAIL_ALREADY_EXISTS,
  USERNAME_NOT_FOUND,
  UNAUTHORZIED_REQUEST,
  PRINCIPAL_NOT_FOUND,
  REGISTER_SUCCESS,
  UNABLE_SENT_EMAIL,
  EMAIL_SERVICE_NOT_AVAIABLE,
  UNPROCESSABLE_ENTITY,
  SERVER_ERROR,
  OUT_OF_STOCK,
  CREATED_SUCCESS,
  UPDATED_SUCCESS,
  DELETED_SUCCESS,
  MISSING_REFRESH_TOKEN,
  INVALID_REFRESH_TOKEN,
  NO_NEGATIVE_QUANTITY,
  PRIVATE_PRODUCT
}
