package com.example.clockee_server.message;

/**
 * MessageKey
 */
public enum MessageKey {
  RESOURCE_NOT_FOUND,
  BAD_REQUEST,
  INVALID_EMAIL,
  EMAIL_ALREADY_EXISTS,
  USERNAME_NOT_FOUND,
  UNAUTHORZIED_REQUEST,
  PRINCIPAL_NOT_FOUND,
  REGISTER_SUCCESS,
  UNABLE_SENT_EMAIL,
  EMAIL_SERVICE_NOT_AVAIABLE,
  UNPROCESSABLE_ENTITY,
  SERVER_ERROR,
}
