version: 2
updates:
  - package-ecosystem: "maven"
    directory: "backend/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(maven):"
      include: "scope"
    labels:
      - "dependencies"
      - "maven"

  - package-ecosystem: "npm"
    directory: "frontend/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
    commit-message:
      prefix: "deps(npm):"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"
