volumes:
  mssql-data:

services:
  clockee-db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: clockee-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SA_PASSWORD:-example_123}
    ports:
      - 1434:1433
    networks:
      - clockee-network
    volumes:
      - mssql-data:/var/opt/mssql
    restart: always
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "${SA_PASSWORD:-example_123}" -Q "SELECT 1" -C -t 30 || exit 1
      interval: 15s
      retries: 5
      start_period: 30s
      timeout: 10s

  sqlserver.configurator:
    image: mcr.microsoft.com/mssql-tools
    container_name: sqlserver.configurator
    depends_on:
      clockee-db:
        condition: service_healthy
    volumes:
      - ./db:/scripts
    entrypoint: ["/bin/bash", "-c", "/scripts/init.sh \"${SA_PASSWORD:-example_123}\""]
    networks:
      - clockee-network

  clockee-mail-server:
    container_name: clockee-mail-server
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - clockee-network



  clockee-server:
    image: trungkieen/clockee-server
    container_name: clockee-server
    environment:
      - DBMS_HOST=clockee-db
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=example_123
      - SPRING_MAIL_HOST=clockee-mail-server
      - FRONTEND_HOST=clockee-web
      - APP_ALLOWED_ORIGINS=http://localhost:3000,http://clockee-web:3000
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://clockee-db;encrypt=true;trustServerCertificate=true;databaseName=clockeedb;useUnicode=true;characterEncoding=UTF-8
    networks:
      - clockee-network
    ports:
      - "8080:8080"
      - "8081:8081"

    depends_on:
      clockee-db:
        condition: service_healthy
      clockee-mail-server:
        condition: service_started

  clockee-web:
    image: trungkieen/clockee-web
    container_name: clockee-web
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

    networks:
      - clockee-network


    depends_on:
      clockee-db:
        condition: service_healthy

      clockee-server:
        condition: service_started


networks:
  clockee-network:
    driver: bridge
