version: '3.8'

volumes:
  mssql-data:

services:
  clockee-db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: clockee-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SA_PASSWORD:-example_123}
    ports:
      - 1433:1433
    networks:
      - clockee-network
    volumes:
      - mssql-data:/var/opt/mssql
    restart: always
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "${SA_PASSWORD:-example_123}" -Q "SELECT 1" -C -t 30 || exit 1
      interval: 15s
      retries: 5
      start_period: 30s
      timeout: 10s

  sqlserver.configurator:
    image: mcr.microsoft.com/mssql-tools
    container_name: sqlserver.configurator
    depends_on:
      clockee-db:
        condition: service_healthy
    volumes:
      - ./db:/scripts
    entrypoint: ["/bin/bash", "-c", "/scripts/init.sh \"${SA_PASSWORD:-example_123}\""]
    networks:
      - clockee-network

  clockee-mail-server:
    container_name: clockee-mail-server
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - clockee-network

networks:
  clockee-network:
    driver: bridge
