
# Build jar stage
FROM maven:3.9.8-amazoncorretto-21 AS build
WORKDIR /app
COPY pom.xml .

RUN mvn dependency:go-offline
COPY src ./src
RUN  mvn package -DskipTests

# Create create runtime image
FROM amazoncorretto:21.0.4
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
COPY upload ./upload
ENTRYPOINT ["java", "-jar", "app.jar"]
