
# Build jar stage
FROM maven:3.9.8-amazoncorretto-21 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN  mvn package -DskipTests
# Use below for cache but require buildx
# RUN --mount=type=cache,target=/root/.m2 mvn -f pom.xml clean package

# Create create runtime image
FROM amazoncorretto:21.0.4
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
COPY upload ./upload
EXPOSE 8080
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]
