// Mock data diplay with paginate when not run server
export const mockPageResponseInfo = {
  content: [
    {
      productId: 1,
      name: "Rolex V3",
      description: "Rolex description",
      actualPrice: 100000,
      sellPrice: 120000,
      type: "4 Quazt",
      stock: 100,
      brandName: "Rolex",
      isActive: true,
      visible: true,
    },
    {
      productId: 1,
      name: "Halminton T12321",
      description: "Halminton description, make your time valueable",
      actualPrice: 200000,
      sellPrice: 220000,
      type: "r Quazt",
      stock: 200,
      brandName: "Haminton",
      isActive: true,
      visible: true,
    },
  ],
  pageable: {
    pageNumber: 0,
    pageSize: 10,
    sort: {
      sorted: false,
      unsorted: true,
      empty: true,
    },
    offset: 0,
    paged: true,
    unpaged: false,
  },
  totalElements: 2,
  totalPages: 1,
  last: true,
  first: true,
  size: 5,
  number: 0,
  sort: {
    sorted: false,
    unsorted: true,
    empty: true,
  },
  numberOfElements: 2,
  empty: false,
};
