import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@fortawesome/fontawesome-free/css/all.min.css";
import { AuthProvider } from "@/lib/hooks/use-auth";
import ToastProvider from "@/lib/providers/toast-provider";
import { CartProvider } from "@/lib/hooks/use-cart";
import { Suspense } from "react";
import { LoadingScreen } from "./components/common/loading";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastProvider>
          <AuthProvider>
            <Suspense fallback={<LoadingScreen />}>
              <CartProvider>{children}</CartProvider>
            </Suspense>
          </AuthProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
