import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer/footer";
import "@fortawesome/fontawesome-free/css/all.min.css";
import { AuthProvider } from "@/lib/hooks/useAuth";
import { Header } from "./components/header/Header";
import ToastProvider from "@/lib/provider/toast.provider";
import { CartProvider } from "@/lib/hooks/useCart";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastProvider>
          <AuthProvider>
            {/*
              <CartProvider >
              </CartProvider>
              */}
            <CartProvider>
              <div className="min-h-screen flex flex-col">
                <Header />

                <main className="flex-1">{children}</main>

                <Footer />
              </div>
            </CartProvider>
          </AuthProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
