name: Testing

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  spring-verify:
    name: Test Spring Boot app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "temurin"
          cache: "maven"


      - name: Verify
        working-directory: ./clockee-server
        run: ./mvnw  verify




  next-verify:
    name: Test Next.js app
    runs-on:  ubuntu-latest
    defaults:
      run:
        working-directory: ./clockee-ui
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: ./clockee-ui/package-lock.json


      - name: Install dependencies
        run: npm install --frozen-lockfile

      # - name: Typescript check
      #   run: npx tsc --noEmit

      - name: Build Project
        run: npm run build
