name: CI

on:
  push:
    branches:
      - "*"

jobs:
  build:
    name: Maven test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "temurin"
          cache: "maven"


      - name: verify
        working-directory: ./clockee-server
        run: ./mvnw  verify
